#!/bin/bash
set -x

function ldpathmunge () {
  case ":${LD_LIBRARY_PATH}:" in
    *:"$1":*) ;;
    *) LD_LIBRARY_PATH=$1:${LD_LIBRARY_PATH}
  esac
}

ldpathmunge /srv/conda/envs/notebook/lib
exec "$@"
